/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#954920",
        "surface-container-highest": "#dee4e3",
        background: "#f5faf9",
        "outline-variant": "#bcc9c8",
        "on-tertiary-fixed-variant": "#77320a",
        "on-primary-fixed": "#002020",
        "secondary-fixed": "#9bf1f0",
        "secondary-container": "#9bf1f0",
        "primary-fixed": "#81f5f4",
        "on-error": "#ffffff",
        "on-background": "#171d1c",
        primary: "#006a6a",
        "tertiary-container": "#d97e51",
        "surface-container": "#eaefee",
        "on-tertiary-container": "#531e00",
        "tertiary-fixed-dim": "#ffb694",
        "surface-variant": "#dee4e3",
        error: "#ba1a1a",
        "on-surface": "#171d1c",
        "secondary-fixed-dim": "#7fd5d4",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-low": "#eff5f4",
        "on-surface-variant": "#3d4949",
        secondary: "#006a6a",
        "surface-bright": "#f5faf9",
        "primary-container": "#1fa6a6",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#edf2f1",
        "on-primary-fixed-variant": "#004f50",
        "on-secondary-container": "#007070",
        "on-tertiary-fixed": "#351000",
        "surface-tint": "#006a6a",
        outline: "#6d7a79",
        "surface-dim": "#d6dbda",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#003435",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004f50",
        "inverse-primary": "#63d8d8",
        "inverse-surface": "#2c3131",
        "on-secondary": "#ffffff",
        success: "#2e7d32",
        "success-container": "#dcefdd",
        warning: "#a15c00",
        "warning-container": "#ffe9cc",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      boxShadow: {
        card: "0 2px 12px 0 rgba(0, 106, 106, 0.08)",
        elevated: "0 8px 24px -4px rgba(0, 106, 106, 0.18)",
      },
    },
  },
  plugins: [],
};
