import {
  Badge,
  Button,
} from "../AstraCompat.jsx";

import {
  Activity,
  AlertTriangle,
  Clock3,
  MessageCircle,
  RefreshCcw,
  Stethoscope,
} from "lucide-react";

function getResultMeta(
  result
) {
  switch (result) {
    case "Emergency":
      return {
        label:
          "Emergency",
        variant:
          "danger",
      };

    case "Urgent":
      return {
        label:
          "Urgent",
        variant:
          "warning",
      };

    case "NonEmergency":
      return {
        label:
          "Non-emergency",
        variant:
          "success",
      };

    default:
      return {
        label:
          result ||
          "Assessment complete",
        variant:
          "default",
      };
  }
}

function formatDate(value) {
  if (!value) {
    return "—";
  }

  const date =
    new Date(value);

  if (
    Number.isNaN(
      date.getTime()
    )
  ) {
    return value;
  }

  return date.toLocaleString(
    "en-ZA"
  );
}

export default function ResultsScreen({
  assessment,
  assessmentResult,
  onFollowUp,
  onRestart,
}) {
  const result =
    assessmentResult
      ?.result;

  const recommendation =
    assessmentResult
      ?.recommendation;

  const meta =
    getResultMeta(
      result
    );

  return (
    <div className="flex flex-col gap-xl">
      <div>
        <Badge
          label={
            meta.label
          }
          variant={
            meta.variant
          }
        />

        <h2 className="mt-md text-title text-text-primary">
          Health
          assessment
        </h2>

        <p className="mt-xs text-label-sm leading-6 text-text-secondary">
          This result was
          generated by the
          PhilaLink symptom
          assessment service
          and recorded in
          your patient
          history.
        </p>
      </div>

      <section className="rounded-corner-lg border border-border-secondary bg-white p-lg">
        <div className="flex items-center gap-md">
          <div className="flex h-10 w-10 items-center justify-center rounded-corner-full bg-brand-tertiary">
            <Activity
              size={17}
              className="text-brand-primary"
            />
          </div>

          <div>
            <p className="text-video-title text-text-secondary">
              Triage
              result
            </p>

            <p className="text-label-sm font-semibold text-text-primary">
              {meta.label}
            </p>
          </div>
        </div>
      </section>

      <section>
        <div className="mb-md flex items-center gap-sm">
          <Stethoscope
            size={17}
            className="text-brand-primary"
          />

          <h3 className="text-label font-semibold text-text-primary">
            Recommendation
          </h3>
        </div>

        <div className="rounded-corner-lg border border-border-secondary bg-white p-lg">
          <p className="text-label-sm leading-6 text-text-primary">
            {recommendation ||
              "No recommendation was returned."}
          </p>
        </div>
      </section>

      <section>
        <div className="mb-md flex items-center gap-sm">
          <Activity
            size={17}
            className="text-brand-primary"
          />

          <h3 className="text-label font-semibold text-text-primary">
            Symptoms
            submitted
          </h3>
        </div>

        <div className="rounded-corner-lg bg-bg-faint p-lg">
          <p className="text-label-sm leading-6 text-text-secondary">
            {Array.isArray(
              assessment
                ?.symptoms
            ) &&
            assessment
              .symptoms
              .length > 0
              ? assessment
                  .symptoms
                  .join(", ")
              : "—"}
          </p>
        </div>
      </section>

      <div className="flex items-start gap-sm rounded-corner-md bg-bg-faint p-md">
        <Clock3
          size={15}
          className="mt-[2px] shrink-0 text-text-secondary"
        />

        <p className="text-video-title leading-5 text-text-secondary">
          Recorded:{" "}
          {formatDate(
            assessmentResult
              ?.createdAt
          )}
        </p>
      </div>

      {result ===
        "Emergency" && (
        <div className="rounded-corner-md bg-danger/10 p-md">
          <div className="flex items-start gap-sm">
            <AlertTriangle
              size={17}
              className="mt-[2px] shrink-0 text-danger"
            />

            <p className="text-label-sm font-medium leading-6 text-danger">
              Follow the
              emergency
              recommendation
              above immediately.
            </p>
          </div>
        </div>
      )}

      <div className="flex flex-col gap-md">
        <Button
          variant="primary"
          iconStart={
            <MessageCircle
              size={15}
            />
          }
          onClick={
            onFollowUp
          }
          className="w-full"
        >
          Ask a follow-up
          question
        </Button>

        <Button
          variant="subtle"
          iconStart={
            <RefreshCcw
              size={15}
            />
          }
          onClick={
            onRestart
          }
          className="w-full"
        >
          Start another
          assessment
        </Button>
      </div>
    </div>
  );
}